import type { Metadata } from "next";
import { Poppins, Oswald, Fira_Code } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import LenisProvider from "../components/lenisProvider";


const poppins = Poppins({
  subsets: ["latin"],
  style: 'normal',
  weight: ['200', '300', '400'],
  variable: "--font-poppins"
});

const fira = Fira_Code({
  subsets: ["latin"],
  style: 'normal',
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-fira"
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ['500', '600', '700'],
  variable: "--font-oswald"
});

export const metadata: Metadata = {
  title: "Portfólio Web - Henrique Handlovics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${oswald.variable} ${fira.variable} antialiased`}
      >
        <LenisProvider>
          <Header />
          {children}
        </LenisProvider>  
      </body>
    </html>
  );
}
